# -*- coding: utf-8 -*-
"""automate_Dicky-Saragih

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UtCJBav9QOFaMAHmQ-si9gAyAYs8AeT9
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import os

def preprocess_emails(input_path="emails.csv", output_path="emails_preprocessed.csv", top_n_features=200):
    print("📥 Memuat dataset...")
    df = pd.read_csv(input_path)

    print(f"🔧 Memilih {top_n_features} fitur teratas...")
    all_features = df.drop(columns=["Email No.", "Prediction"])
    top_features = all_features.sum().sort_values(ascending=False).head(top_n_features).index.tolist()

    # Ambil hanya top-n fitur
    X = all_features[top_features]
    y = df["Prediction"]

    # Standardisasi
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    X_scaled_df = pd.DataFrame(X_scaled, columns=top_features)

    # Gabungkan kembali dengan label
    df_preprocessed = pd.concat([X_scaled_df, y.reset_index(drop=True)], axis=1)

    # Simpan hasil
    if os.path.dirname(output_path):
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
    df_preprocessed.to_csv(output_path, index=False)
    print(f"✅ Hasil preprocessing disimpan di: {output_path}")

if __name__ == "__main__":
    preprocess_emails()

