# -*- coding: utf-8 -*-
"""automate_Dicky-Saragih

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UtCJBav9QOFaMAHmQ-si9gAyAYs8AeT9
"""

import pandas as pd
import numpy as np
import os

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

def preprocess_fish_dataset(input_path="Fish.csv", output_path="namadataset_preprocessing.csv"):
    # Load dataset
    df = pd.read_csv(input_path)

    # Fitur dan target
    numerical_features = ['Length1', 'Length2', 'Length3', 'Height', 'Width']
    categorical_features = ['Species']
    target_column = 'Weight'

    # Definisi pipeline numerik
    numeric_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='mean')),
        ('scaler', StandardScaler())
    ])

    # Definisi pipeline kategorikal
    categorical_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encoder', OneHotEncoder(handle_unknown='ignore'))
    ])

    # Gabungkan pipeline
    preprocessor = ColumnTransformer(transformers=[
        ('num', numeric_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

    # Pisahkan X dan y
    X = df.drop(columns=[target_column])
    y = df[target_column]

    # Jalankan preprocessing
    X_processed = preprocessor.fit_transform(X)

    # Ambil nama kolom hasil encoding
    ohe_columns = preprocessor.named_transformers_['cat']['encoder'].get_feature_names_out(categorical_features)
    processed_columns = np.concatenate([numerical_features, ohe_columns])

    # Gabungkan hasil
    X_processed_df = pd.DataFrame(X_processed, columns=processed_columns)
    df_final = pd.concat([X_processed_df, y.reset_index(drop=True)], axis=1)

    # Simpan hasil
    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    df_final.to_csv(output_path, index=False)
    print(f"✅ Dataset berhasil disimpan di: {output_path}")