name: Data Preprocessing Workflow

# Trigger workflow saat ada push ke branch apapun
# dan file di folder namadataset_raw atau script .py berubah
on:
  push:
    paths:
      - 'namadataset_raw/**'
      - 'preprocessing/*.py'

jobs:
  preprocess:
    name: Run Preprocessing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_dicky_saragih.py \
            --input_path namadataset_raw/Fish.csv \
            --output_path preprocessing/namadataset_preprocessing.csv

      - name: List output files
        run: |
          echo "Hasil preprocessing:"
          ls -lh preprocessing/
